### ISSUE TITLE
Async error when including partials

### ISSUE THREAD

**Issue by carolinerusso** [tuanpham-dev/gulp-liquidjs#4]
When partials are included (via `{% include %}`), the task won't complete and throws an error: 
`The following tasks did not complete: [TASK_NAME] 
Did you forget to signal async completion?`

When the {% include %} is removed, the task completes successfully.

`gulp -v
4.0.2`

### To reproduce:

.gulpfile.js

````
const { src, watch, series, dest, lastRun, parallel } = require('gulp');
const liquid = require('gulp-liquidjs')

function html() {
  return src(`source/html/*.html`)
    .pipe(liquid({
      engine: {
        extname: '.html',
        root: ['source/html/partials']
      }
    }))
    .pipe(dest(`build/html`))
}

exports.html = html;
````

In source/html/index.html:
````
<!DOCTYPE html>
<html>
<head>
	<title>Name</title>
</head>
<body>
	{% assign title = "Testing" %}
	<h1>{{title}}</h1>
	{% include 'test.html' %} 
</body>
</html>
````

In source/html/partials/test.html:
````
<p>I am a partial</p>
````

**Comment by tuanpham-dev** [comment]
@carolinerusso - Please use module `@tuanpham-dev/gulp-liquidjs`. It's different from `gulp-liquidjs`.
